### ISSUE TITLE
Add commands before Password and after login

### ISSUE THREAD

**Issue by ciccior2004** [supechicken/ChromeOS-AutoLogin#1]
Very useful and easy to install solution.
I had to do it with an Esp32-c3 and BLE keyboard library.
It would be perfect if it were possible to send a keystroke before the password for example CTRL+ALT+SHIFT+t (tablet mode) and another keystroke after login for example ALT+1 (launching the first app in the taskbar)

**Comment by ciccior2004** [comment]
> Very useful and easy to install solution. I had to do it with an Esp32-c3 and BLE keyboard library. It would be perfect if it were possible to send a keystroke before the password for example CTRL+ALT+SHIFT+t (tablet mode) and another keystroke after login for example ALT+1 (launching the first app in the taskbar)

I have modified "autologin.cr" with this :

# press SHIFT+ALT+CTRL+t
Uinput.emit_keyevent(Uinput::EV_KEY, 42, 1)
Uinput.emit_keyevent(Uinput::EV_KEY, 56, 1)
Uinput.emit_keyevent(Uinput::EV_KEY, 29, 1)
Uinput.emit_keyevent(Uinput::EV_KEY, 20, 1)
Uinput.emit_keyevent(Uinput::EV_SYN, 0, 0)
Uinput.emit_keyevent(Uinput::EV_KEY, 42, 0)
Uinput.emit_keyevent(Uinput::EV_KEY, 56, 0)
Uinput.emit_keyevent(Uinput::EV_KEY, 29, 0)
Uinput.emit_keyevent(Uinput::EV_KEY, 20, 0)
Uinput.emit_keyevent(Uinput::EV_SYN, 0, 0)
sleep(0.02)

# press enter
Uinput.emit_keyevent(Uinput::EV_KEY, 28, 1)
Uinput.emit_keyevent(Uinput::EV_SYN, 0, 0)
Uinput.emit_keyevent(Uinput::EV_KEY, 28, 0)
Uinput.emit_keyevent(Uinput::EV_SYN, 0, 0)
sleep(4.00)

# press ALT+1
Uinput.emit_keyevent(Uinput::EV_KEY, 56, 1)
Uinput.emit_keyevent(Uinput::EV_KEY, 2, 1)
Uinput.emit_keyevent(Uinput::EV_SYN, 0, 0)
sleep(0.05)
Uinput.emit_keyevent(Uinput::EV_KEY, 56, 0)
Uinput.emit_keyevent(Uinput::EV_KEY, 2, 0)
Uinput.emit_keyevent(Uinput::EV_SYN, 0, 0)
sleep(1.00)

and works very well. ( the sleep time depends from your device )

Thanks a lot to SupeChicken666!!!

**Comment by supechicken** [comment]
Glad to know this project is helpful for you :)
